// ── Pytania jawne CKE ────────────────────────────────────
const jawneData = [
  { num:1, book:'Biblia (Ks. Hioba)', priority:'high',
    q:'Motyw cierpienia niezawinionego. Omów zagadnienie na podstawie znanych Ci fragmentów Księgi Hioba. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Hiob traci majątek, dzieci i zdrowie – Bóg pozwala szatanowi wypróbować jego wiarę. Cierpienie niezawinione to problem filozofii i teologii (theodiceum). Hiob odwołuje się wprost do Boga zamiast przyjmować argumenty przyjaciół. Kontekst: Camus – Dżuma (śmierć dziecka jako argument przeciw teodycei), Chrystus (cierpienie niewinnego).' },
  { num:2, book:'Biblia (Ks. Koheleta)', priority:'med',
    q:'Człowiek wobec niestałości świata. Omów zagadnienie na podstawie znanych Ci fragmentów Księgi Koheleta. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'"Vanitas vanitatum et omnia vanitas" – wszystko przemija. Kohelet radzi cieszyć się chwilą (carpe diem). Kontekst: Horacy – carpe diem, barok – vanitas, treny Kochanowskiego.' },
  { num:3, book:'Biblia (Apokalipsa)', priority:'med',
    q:'Wizja końca świata. Omów zagadnienie na podstawie znanych Ci fragmentów Apokalipsy. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Czterej jeźdźcy, bestia 666, Nowe Jeruzalem – eschatologia chrześcijańska. Kontekst: Rok 1984 (dystopia), Wesele (wizyjność), malarstwo Dürera.' },
  { num:4, book:'Mitologia (Parandowski)', priority:'med',
    q:'Poświęcenie się w imię wyższych wartości. Omów zagadnienie na podstawie Mitologii Jana Parandowskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Prometeusz – ogień dla ludzkości; Achilles – chwalebna śmierć; Orfeusz – miłość pokonuje śmierć. Kontekst: Dziady III (Konrad, ks. Piotr), Makbet (kontrast).' },
  { num:5, book:'Mitologia (Parandowski)', priority:'high',
    q:'Problematyka winy i kary. Omów zagadnienie na podstawie Mitologii Jana Parandowskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Hybris → nemezis: Syzyf, Tantalos, Edyp. Bogowie strzegą porządku (dike). Kontekst: Makbet, Zbrodnia i kara, Antygona.' },
  { num:6, book:'Mitologia (Parandowski)', priority:'med',
    q:'Miłość silniejsza niż śmierć. Omów zagadnienie na podstawie Mitologii Jana Parandowskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Orfeusz i Eurydyka – miłość pokonuje Hades, lecz nieufność niszczy. Kontekst: Lalka (destrukcyjna miłość), Romeo i Julia.' },
  { num:7, book:'Homer, Iliada', priority:'high',
    q:'Heroizm jako postawa człowieka w zmaganiu się z losem. Omów zagadnienie na podstawie fragmentów Iliady. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Achilles – arete, krótkie lecz chwalebne życie; Hektor – lojalność i godna śmierć. Fatum nieodwracalne – bohater decyduje o sposobie przyjęcia losu. Kontekst: Antygona, Potop, Dziady III.' },
  { num:8, book:'Sofokles, Antygona', priority:'high',
    q:'Prawa boskie a prawa ludzkie. Omów zagadnienie na podstawie Antygony Sofoklesa. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Antygona (physis – prawo boskie) vs Kreon (nomos – prawo ludzkie). Oboje płacą cenę. Kontekst: Rok 1984, Biblia (prawa Boże vs cesarskie).' },
  { num:9, book:'Sofokles, Antygona', priority:'med',
    q:'Człowiek wobec przeznaczenia. Omów zagadnienie na podstawie Antygony Sofoklesa. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Fatum rodu Edypa nieodwracalne. Antygona przyjmuje los z godnością. Kontekst: Makbet (człowiek szuka własnego losu), stoicyzm.' },
  { num:13, book:'Szekspir, Makbet', priority:'high',
    q:'Moralna odpowiedzialność za czyny. Omów zagadnienie na podstawie Makbeta Szekspira. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Makbet sam dokonuje wyboru – wiedźmy i Lady Makbet inspirują, nie decydują. Kara wewnętrzna (wizje) poprzedza zewnętrzną. Kontekst: Zbrodnia i kara, prawo karne.' },
  { num:14, book:'Szekspir, Makbet', priority:'high',
    q:'Czy człowiek decyduje o własnym losie? Omów zagadnienie na podstawie Makbeta Szekspira. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Wiedźmy przepowiadają, nie nakazują – Makbet sam decyduje. Charakter jest przeznaczeniem. Kontekst: Antygona (fatum), determinizm vs woluntaryzm.' },
  { num:15, book:'Szekspir, Makbet', priority:'high',
    q:'Jaki wpływ na człowieka ma sprawowanie przez niego władzy? Omów zagadnienie na podstawie Makbeta Szekspira. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Władza korumpuje – Makbet traci człowieczeństwo, przyjaźń, spokój. Lady Makbet – obłęd. Lord Acton: "władza deprawuje absolutnie". Kontekst: Rok 1984, Dziady III.' },
  { num:21, book:'Mickiewicz, Dziady III', priority:'high',
    q:'Losy młodzieży polskiej pod zaborami. Omów zagadnienie na podstawie Dziadów III Mickiewicza. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Represje rosyjskie po 1823 r. Konrad, Rollison i inni więźniowie – pokolenie składające ofiarę z wolności. Kontekst: Inny świat, Rok 1984.' },
  { num:22, book:'Mickiewicz, Dziady III', priority:'high',
    q:'Mesjanizm jako romantyczna idea poświęcenia. Omów zagadnienie na podstawie Dziadów III Mickiewicza. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Polska = Chrystus narodów (Widzenie ks. Piotra). Konrad dąży do mesjanistycznej roli. Kontekst: Biblia, krytyka mesjanizmu (Norwid).' },
  { num:23, book:'Mickiewicz, Dziady III', priority:'high',
    q:'Postawy społeczeństwa polskiego wobec zaborcy. Omów zagadnienie na podstawie Dziadów III Mickiewicza. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Salon Warszawski: konformiści balują, kolaboranci schlebiają Rosjanom, nieliczni zachowują godność. Kontekst: Wesele, Przedwiośnie.' },
  { num:27, book:'Mickiewicz, Dziady III', priority:'high',
    q:'Walka dobra ze złem o duszę ludzką. Omów zagadnienie na podstawie Dziadów III Mickiewicza. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Anioły i diabły walczą o Konrada. Bunt zbliża do zła, pokora ks. Piotra ratuje. Kontekst: Makbet, Faust Goethego.' },
  { num:28, book:'Mickiewicz, Dziady III', priority:'high',
    q:'Czym dla człowieka może być wolność? Omów zagadnienie na podstawie Dziadów III Mickiewicza. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Wolność polityczna, duchowa, moralna. Więźniowie zachowują wolność wewnętrzną. Paradoks: wolność bez miłości = pycha. Kontekst: Rok 1984, Antygona, Sartre.' },
  { num:30, book:'Prus, Lalka', priority:'high',
    q:'Miłość – siła destrukcyjna czy motywująca do działania? Omów zagadnienie na podstawie Lalki Prusa. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Obsesja Wokulskiego do Izabeli niszczy. Miłość Rzeckiego do ideałów – motywuje. Kontekst: Makbet (destrukcja), Mitologia (Orfeusz).' },
  { num:32, book:'Prus, Lalka', priority:'high',
    q:'Jaką rolę odgrywają majątek i pochodzenie w relacjach międzyludzkich? Omów zagadnienie na podstawie Lalki Prusa. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Wokulski mimo fortuny odrzucony przez arystokrację. Izabela – zdegenerowana szlachta ceniąca pozory. Kontekst: Wesele, Skąpiec.' },
  { num:33, book:'Prus, Lalka', priority:'high',
    q:'Konfrontacja marzeń z rzeczywistością. Omów zagadnienie na podstawie Lalki Prusa. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Wokulski – idealna miłość vs rozczarowanie. Rzecki – Napoleon nie powróci. Romantyczne ideały zderzają się z pozytywistyczną rzeczywistością. Kontekst: Przedwiośnie, Rok 1984.' },
  { num:42, book:'Wyspiański, Wesele', priority:'high',
    q:'Co utrudnia porozumienie między przedstawicielami różnych grup społecznych? Omów zagadnienie na podstawie Wesela Wyspiańskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Inteligencja i chłopstwo różnią kultury, historia, interesy. Chłopi pamiętają rzeź galicyjską. Kontekst: Lalka, Tango, Bourdieu.' },
  { num:49, book:'Żeromski, Przedwiośnie', priority:'high',
    q:'Wojna i rewolucja jako źródła doświadczeń człowieka. Omów zagadnienie na podstawie Przedwiośnia Żeromskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Cezary formuje się przez rewolucję w Baku i wojnę 1920. Przemoc niszczy i hartuje. Kontekst: Inny świat, Zbrodnia i kara.' },
  { num:50, book:'Żeromski, Przedwiośnie', priority:'high',
    q:'Różne wizje odbudowy Polski po odzyskaniu niepodległości. Omów zagadnienie na podstawie Przedwiośnia Żeromskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Szklane domy (utopia), Gajowiec (reformizm), komuniści (rewolucja). Żeromski nie daje odpowiedzi. Kontekst: historia II RP, Wesele.' },
  { num:55, book:'Gombrowicz, Ferdydurke', priority:'high',
    q:'Człowiek wobec presji otoczenia. Omów zagadnienie na podstawie fragmentów Ferdydurke Gombrowicza. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'"Upupienie" – społeczeństwo narzuca formy. Autentyczność niemożliwa. Sartre: "Piekło to inni". Kontekst: Rok 1984, psychologia konformizmu.' },
  { num:56, book:'Borowski, Proszę państwa do gazu', priority:'high',
    q:'"Człowiek zlagrowany" jako ofiara zbrodniczego systemu. Omów zagadnienie na podstawie utworu Borowskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Dehumanizacja w Auschwitz – człowiek traci empatię dla przeżycia. Nie wina jednostki – system. Kontekst: Inny świat, Hannah Arendt (banalność zła).' },
  { num:58, book:'Herling-Grudziński, Inny świat', priority:'high',
    q:'Konsekwencje zniewolenia człowieka. Omów zagadnienie na podstawie fragmentów Innego świata. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Kolaboracja, opór, rezygnacja, szaleństwo. Kostylew odmawia pracy – umiera z godnością. Kontekst: Proszę państwa do gazu, Rok 1984, Frankl.' },
  { num:62, book:'Camus, Dżuma', priority:'high',
    q:'Co skłania człowieka do poświęceń? Omów zagadnienie na podstawie Dżumy Camusa. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Rieux – obowiązek; Tarrou – poczucie winy; Grand – bycie pożytecznym. Egzystencjalistyczna solidarność. Kontekst: Sonia (Zbrodnia i kara), Prometeusz.' },
  { num:65, book:'Camus, Dżuma', priority:'high',
    q:'Jakie postawy przyjmuje człowiek wobec zła? Omów zagadnienie na podstawie Dżumy Camusa. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Walka (Rieux), ucieczka (Rambert), kolaboracja (Cottard), interpretacja teologiczna (Paneloux). Kontekst: Rok 1984, Makbet, II wojna.' },
  { num:66, book:'Orwell, Rok 1984', priority:'high',
    q:'Czy możliwe jest zbudowanie doskonałego państwa? Omów zagadnienie na podstawie Roku 1984 Orwella. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Każda utopia oparta na terrorze staje się dystopią. Władza jako cel sam w sobie. Kontekst: Platon (Republika), Przedwiośnie, historia komunizmu.' },
  { num:67, book:'Orwell, Rok 1984', priority:'high',
    q:'Jak zachować wolność w państwie totalitarnym? Omów zagadnienie na podstawie Roku 1984 Orwella. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Winston: pamiętnik, miłość, Braterstwo – wszystko zniszczone (pokój 101). Kontekst: Inny świat, Dziady III, Fromm.' },
  { num:68, book:'Orwell, Rok 1984', priority:'high',
    q:'Znaczenie propagandy w państwie totalitarnym. Omów zagadnienie na podstawie Roku 1984 Orwella. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Teleekrany, Min. Prawdy, Dwie Minuty Nienawiści, Newspeak. Manipulacja językiem = manipulacja myślą (Sapir-Whorf). Kontekst: Dziady III, teorie mediów.' },
  { num:69, book:'Orwell, Rok 1984', priority:'high',
    q:'Nowomowa jako sposób na ograniczenie wolności człowieka. Omów zagadnienie na podstawie Roku 1984 Orwella. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Newspeak eliminuje słowa wolności → Crimethink niemożliwy. Wittgenstein: granice języka = granice świata. Kontekst: Ferdydurke, lingwistyka.' },
  { num:71, book:'Mrożek, Tango', priority:'high',
    q:'Konflikt pokoleń. Omów zagadnienie na podstawie Tanga Mrożka. W swojej odpowiedzi uwzględnij również wybrany kontekst.',
    ans:'Rodzice – liberalizm; Artur – konserwatyzm (paradoks). Edek (brutalność) wygrywa. Kontekst: Skąpiec, Dziady III, socjologia pokoleń.' },
];

// ── Quiz ────────────────────────────────────────────────
const plQuizData = [
  { type:'abcd', q:"Kim jest narrator w Lalce Prusa?",
    options:["A) Wokulski","B) Narrator auktorialny + pamiętnik Rzeckiego","C) Izabela Łęcka","D) Narrator 1-os. – Rzecki"],
    correct:1, exp:"Dwie warstwy: obiektywny narrator 3-os. i subiektywny pamiętnik Rzeckiego." },
  { type:'abcd', q:"Czym jest chocholi taniec w Weselu Wyspiańskiego?",
    options:["A) Radosną sceną weselną","B) Symbolem marazmu i niemocy narodu","C) Tańcem śmierci","D) Metaforą buntu chłopskiego"],
    correct:1, exp:"Chocholi taniec = zaśpienie narodu, niemożność czynu wyzwoleńczego." },
  { type:'abcd', q:"Co symbolizuje Wielka Improwizacja Konrada w Dziadach III?",
    options:["A) Pokorne przyjęcie cierpienia","B) Bunt prometejski – żądanie władzy nad duszami","C) Pakt z diabłem","D) Modlitwę o wyzwolenie"],
    correct:1, exp:"Konrad żąda rządu dusz dla narodu – bunt prometejski." },
  { type:'abcd', q:"Kto stworzył pojęcie człowiek zlagrowany?",
    options:["A) Herling-Grudziński","B) Kapuściński","C) Tadeusz Borowski","D) Hanna Krall"],
    correct:2, exp:"Borowski – człowiek dehumanizowany przez system obozowy." },
  { type:'abcd', q:"Jaką funkcję pełni Newspeak w Roku 1984?",
    options:["A) Ułatwia komunikację","B) Promuje kulturę robotniczą","C) Ogranicza myślenie przez eliminację słów buntowniczych","D) Jest językiem klasy wyższej"],
    correct:2, exp:"Nowomowa → Crimethink (myśl buntownicza) niemożliwa do wyrażenia." },
  { type:'abcd', q:"Kim jest Sonia Marmieładowa w Zbrodni i karze?",
    options:["A) Córką Raskolnikowa","B) Agentką policji","C) Prostytutką, która przez miłość prowadzi Raskolnikowa do przemiany","D) Siostrą Raskolnikowa"],
    correct:2, exp:"Sonia = chrześcijańska miłość i miłosierdzie, prowadzi do odrodzenia." },
  { type:'abcd', q:"Jaką postawę reprezentuje Starzec w Romantyczności Mickiewicza?",
    options:["A) Wiarę w duchy","B) Racjonalizm oświeceniowy","C) Chrześcijański mistycyzm","D) Nihilizm"],
    correct:1, exp:"Starzec (Śniadecki) = empiryzm i rozum oświeceniowy." },
  { type:'abcd', q:"W którym roku rozgrywa się akcja Wesela Wyspiańskiego?",
    options:["A) 1830","B) 1863","C) 1900","D) 1918"],
    correct:2, exp:"Wesele oparte na prawdziwym weselu z 1900 r. w Bronowicach." },
  { type:'abcd', q:"Czym jest hybris w tragedii greckiej?",
    options:["A) Mądrość bogów","B) Pycha prowadząca do upadku bohatera","C) Miłość tragiczna","D) Kodeks honorowy"],
    correct:1, exp:"Hybris (pycha) → nemezis (kara boska). Edyp, Makbet." },
  { type:'abcd', q:"Co łączy Antygonę i Winstona Smitha z Roku 1984?",
    options:["A) Poddają się władzy","B) Buntują się przeciw niesprawiedliwym prawom","C) Uciekają z kraju","D) Zakochują się w osobach z wyższej klasy"],
    correct:1, exp:"Oboje wybierają sumienie kosztem życia." },
  { type:'abcd', q:"Kto jest autorem Lalki?",
    options:["A) Stefan Żeromski","B) Henryk Sienkiewicz","C) Bolesław Prus","D) Władysław Reymont"],
    correct:2, exp:"Bolesław Prus, powieść wydana 1890." },
  { type:'abcd', q:"Co symbolizuje Złoty Róg w Weselu?",
    options:["A) Miłość do ziemi","B) Sygnał do powstania, który zostaje utracony","C) Bogactwo chłopstwa","D) Symbol ślubu"],
    correct:1, exp:"Złoty Róg = wezwanie do walki. Zgubiony przez Gospodarza – niemoc narodu." },
  { type:'open', q:"Wyjaśnij (2–3 zdania), na czym polega mesjanizm w Dziadach III Mickiewicza.",
    exp:"Mesjanizm = Polska jako Chrystus narodów – cierpi niewinnie (rozbiory = ukrzyżowanie), by odkupić Europę (niepodległość = zmartwychwstanie). Widzenie ks. Piotra przedstawia tę alegorię. Mickiewicz łączy patriotyzm z religią." },
  { type:'abcd', q:"Jakie epoki łączy postać Wokulskiego w Lalce?",
    options:["A) Barok i Oświecenie","B) Romantyzm i Pozytywizm","C) Renesans i Romantyzm","D) Modernizm i Dwudziestolecie"],
    correct:1, exp:"Wokulski = romantyk z ducha (miłość), pozytywista z działania (praca, nauka)." },
  { type:'abcd', q:"Kim jest Edek w Tangu Mrożka?",
    options:["A) Synem Artura","B) Bratem Stomila","C) Lokatorem, który ostatecznie przejmuje władzę siłą","D) Ojcem Artura"],
    correct:2, exp:"Edek = prymitywna siła bez wartości, wygrywa gdy idealizm Artura ponosi klęskę." },
];

// ── Fiszki ───────────────────────────────────────────────
const plFiszki = [
  { front:'Mesjanizm', back:'Polska = Chrystus narodów – cierpi niewinnie, by odkupić Europę.\nDziady III – Widzenie ks. Piotra.' },
  { front:'Hybris', back:'Pycha (gr.) → grzech wobec bogów → nemezis (kara).\nEdyp, Syzyf, Makbet.' },
  { front:'Człowiek zlagrowany', back:'Borowski – więzień obozu tracący empatię dla przeżycia.\nNie wina jednostki – wina systemu.' },
  { front:'Vanitas vanitatum', back:'"Marność nad marnościami" – Kohelet.\nKluczowy motyw baroku i średniowiecza.' },
  { front:'Chocholi taniec', back:'Wesele Wyspiańskiego – symbol marazmu narodu.\nGoście tańczą w kółko, nie podejmując żadnego czynu.' },
  { front:'Nowomowa (Newspeak)', back:'Rok 1984 Orwella – eliminuje słowa wolności.\nCrimethink → niemożliwy do wyrażenia = niemożliwy do pomyślenia.' },
  { front:'Danse macabre', back:'Śmierć zabiera wszystkich bez względu na stan.\nRozmowa Mistrza Polikarpa, chocholi taniec w Weselu.' },
  { front:'Teodyceum', back:'Dlaczego Bóg dopuszcza cierpienie niewinnych?\nKsiega Hioba, Dżuma Camusa.' },
  { front:'Fatum', back:'Nieuchronny los w tragedii greckiej.\nAntygona, Edyp – nie uciekają. Makbet sam przyciąga swoje fatum.' },
  { front:'Praca organiczna', back:'Pozytywizm – każdy pracuje dla dobra społeczeństwa jak narząd w organizmie.\nWokulski (Lalka), Orzeszkowa.' },
  { front:'Wielka Improwizacja', back:'Dziady III – Konrad buntuje się wobec Boga, żądając władzy nad duszami.\nSzczyt romantycznego indywidualizmu.' },
  { front:'Konrad vs Ksiądz Piotr', back:'Dwie postawy wobec Boga (Dziady III):\nKonrad – bunt prometejski\nKs. Piotr – pokora chrześcijańska.' },
];

// ── Egzamin próbny ───────────────────────────────────────
const plEgzaminData = [
  { type:'abcd', q:'1. Czym jest Wielka Improwizacja w Dziadach III?',
    options:['A) Modlitwa Konrada','B) Bunt prometejski – Konrad żąda od Boga władzy nad duszami','C) Scena sądu nad Rosjanami','D) Wizja ks. Piotra'], correct:1 },
  { type:'abcd', q:'2. Kto jest autorem Lalki?',
    options:['A) Stefan Żeromski','B) Henryk Sienkiewicz','C) Bolesław Prus','D) Władysław Reymont'], correct:2 },
  { type:'abcd', q:'3. Danse macabre to motyw związany z:',
    options:['A) Miłością dworską','B) Równością wszystkich wobec śmierci','C) Heroizmem rycerskim','D) Buntem narodowym'], correct:1 },
  { type:'abcd', q:'4. Ministerstwo Prawdy w Roku 1984 zajmuje się:',
    options:['A) Produkcją żywności','B) Szkoleniem Policji Myśli','C) Fałszowaniem historii i propagandą','D) Nadzorowaniem teleekranów'], correct:2 },
  { type:'abcd', q:'5. Raskolnikow zabija lichwiarkę, ponieważ:',
    options:['A) Chce pieniędzy dla ubogich','B) Niezwykłe jednostki mają prawo łamać normy moralne (jego teoria)','C) Został zaszantażowany','D) Działa pod wpływem rewolucjonistów'], correct:1 },
  { type:'abcd', q:'6. Który utwór jest świadectwem o Powstaniu w Getcie?',
    options:['A) Proszę państwa do gazu','B) Inny świat','C) Zdążyć przed Panem Bogiem','D) Rok 1984'], correct:2 },
  { type:'abcd', q:'7. Hybris w kulturze antycznej oznacza:',
    options:['A) Odwagę w boju','B) Pychę prowadzącą do upadku','C) Miłość ojczyzny','D) Mądrość filozoficzną'], correct:1 },
  { type:'open', q:'8. Wymień dwa sposoby, w jaki Oceania w Roku 1984 kontroluje obywateli.',
    exp:'Teleekrany (stały nadzór), Policja Myśli, fałszowanie historii (Min. Prawdy), Newspeak, Dwie Minuty Nienawiści, system donosicielstwa.' },
  { type:'open', q:'9. Na czym polega mesjanizm u Mickiewicza? (2 zdania)',
    exp:'Polska jak Chrystus cierpi niewinnie (rozbiory = ukrzyżowanie), by odkupić Europę (niepodległość = zmartwychwstanie). Widzenie ks. Piotra w Dziadach III przedstawia tę alegorię.' },
  { type:'abcd', q:'10. Groteska w Ferdydurke Gombrowicza polega na:',
    options:['A) Realistycznym opisie epoki','B) Absurdalnych sytuacjach demaskujących fałsz konwenansów','C) Heroizmie romantycznym','D) Szczegółowej psychologii postaci'], correct:1 },
];